version: "3"

services:

  mongodb:
    container_name: mongodb
    image: mongo:6.0
    volumes:
      - ~/mongo:/data/db
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=mXd2lPgdYhCtgxtR
      - MONGO_INITDB_DATABASE=admin
    networks:
      - project-costs-network

networks:
  project-costs-network:
    driver: bridge
