POST http://localhost:8000/api/projects
Content-Type: application/json

{
    "name": "CapZone",
    "cost": 1000,
    "description": "A Compliance US Project",
    "category": {
        "description": "Development"
    },
    "services": [
        {
             "name": "DevOps",
             "budget": 10000
        }
    ]
}

###
GET http://localhost:8000/api/projects

###
GET http://localhost:8000/api/projects/{id}

###
DELETE  http://localhost:8000/api/projects/{id}

###
PUT http://localhost:8000/api/projects/{id}
Content-Type: application/json

{
    "name": "CapZone Analytics",
    "cost": 1000,
    "description": "Infrastructure"
}

###

POST http://localhost:8000/api/categories
Content-Type: application/json

{
    "description": "Development"
}

###
GET http://localhost:8000/api/categories

###
GET http://localhost:8000/api/categories/{id}

###
DELETE  http://localhost:8000/api/categories/{id}

###
PUT http://localhost:8000/api/categories/{id}
Content-Type: application/json

{
    "description": "Infrastructure"
}

###

POST http://localhost:8000/api/services
Content-Type: application/json

{
    "name": "DevOps",
    "budget": 10000
}

###
GET http://localhost:8000/api/services

###
GET http://localhost:8000/api/services/{id}

###
DELETE  http://localhost:8000/api/services/{id}

###
PUT http://localhost:8000/api/services/{id}

Content-Type: application/json

{
    "name": "QA",
    "budget": 10000
}
###